/// @file core.hpp
/// @brief Convenience umbrella header that includes all of trux's
///        public headers. Include this for quick access to the whole
///        library; include individual headers directly to minimize
///        compile-time dependencies.

#pragma once

#include "trux/async/channel.hpp"
#include "trux/async/executor.hpp"
#include "trux/async/spawn.hpp"
#include "trux/command/command.hpp"
#include "trux/component/border.hpp"
#include "trux/component/checkbox.hpp"
#include "trux/component/component.hpp"
#include "trux/component/component_flags.hpp"
#include "trux/component/dialog.hpp"
#include "trux/component/dropdown.hpp"
#include "trux/component/label.hpp"
#include "trux/component/list.hpp"
#include "trux/component/menu.hpp"
#include "trux/component/paragraph.hpp"
#include "trux/component/split.hpp"
#include "trux/component/text_input.hpp"
#include "trux/focus/focus_manager.hpp"
#include "trux/input/event.hpp"
#include "trux/input/event_parser.hpp"
#include "trux/input/input.hpp"
#include "trux/input/key.hpp"
#include "trux/input/keymap.hpp"
#include "trux/input/modifiers.hpp"
#include "trux/input/mouse.hpp"
#include "trux/layout/layout.hpp"
#include "trux/layout/position.hpp"
#include "trux/layout/rect.hpp"
#include "trux/layout/region.hpp"
#include "trux/layout/size.hpp"
#include "trux/renderer/cell.hpp"
#include "trux/renderer/cell_buffer.hpp"
#include "trux/renderer/draw_command.hpp"
#include "trux/renderer/draw_command_buffer.hpp"
#include "trux/renderer/renderer.hpp"
#include "trux/style/color.hpp"
#include "trux/style/style.hpp"
#include "trux/terminal/ansi.hpp"
#include "trux/terminal/terminal.hpp"